configfile: "./config.yaml"
workdir: "/home/pkalverla1/Urban-M4/experiments/snakemake"
envvars:
    "NETCDF",


DOMAINS = ['d01', 'd02', 'd03', 'd04']
TIMES = range(13)  # TODO: include dates, make more flexible?

rule all:
    input:
        expand("wrfout_{d}_2024-04-19_00:00:00", d=DOMAINS)

rule CREATE_WORKDIR:
    input: workflow.source_path("namelist.wps"), workflow.source_path("GEOGRID.TBL"), workflow.source_path("namelist.input")
    output: "namelist.wps", "GEOGRID.TBL", "namelist.input"
    shell: "cp {input} ."

rule GEOGRID:
    input: "namelist.wps", "GEOGRID.TBL"
    output: expand("output/geogrid/geo_em.{domain}.nc", domain=DOMAINS)
    shell:
        f"""
        mkdir -p output/geogrid
        {config['WPS_HOME']}/geogrid.exe
        """

rule W2W:
    input: rules.GEOGRID.output
    log: "w2w.log"
    shell:
        f"""
        cd output/geogrid
        w2w . /projects/0/prjs0914/wrf-data/default/lcz/amsterdam_lcz4_clean.tif ./geo_em.d04.nc v4.5.2
        mv geo_em.d01_61.nc geo_em.d01.nc
        mv geo_em.d02_61.nc geo_em.d02.nc
        mv geo_em.d03_61.nc geo_em.d03.nc
        mv geo_em.d04_LCZ_params.nc geo_em.d04.nc
        """


rule UNGRIB:
    input: "namelist.wps"
    output: [f"FILE:2024-04-19_{t:02d}" for t in TIMES]
    shell: f"""
        {config['WPS_HOME']}/link_grib.csh {config['DATA_HOME']}/real-time/gfs-data/*
        cp {config['WPS_HOME']}/ungrib/Variable_Tables/Vtable.GFS Vtable
        {config['WPS_HOME']}/ungrib.exe
        rm GRIBFILE.*

    """
    # TODO: move gribfiles to own dir, but not supported by WPS, so after metgrid

rule METGRID:
    input:
        "namelist.wps",
        rules.UNGRIB.output,
        rules.GEOGRID.output,
        rules.W2W.log,
    output:
        expand("output/metgrid/met_em.{d}.2024-04-19_{t:02d}:00:00.nc", d=DOMAINS, t=TIMES)
    shell:
        f"""
        mkdir -p output/metgrid
        cp {config['WPS_HOME']}/metgrid/METGRID.TBL.ARW METGRID.TBL
        {config['WPS_HOME']}/metgrid.exe

        # Cleanup ungrib stuff
        mkdir -p output/ungrib
        mv FILE* output/ungrib
        """

rule REAL:
    input:
        "namelist.input",
        rules.METGRID.output,
    output:
        expand("wrfinput_{d}", d=DOMAINS),
        "wrfbdy_d01"
    shell:
        f"""
        ln -srf /output/metgrid/* .
        {config['WRF_HOME']}/run/real.exe
        rm met_em*
        """

rule WRF:
    input:
        "namelist.input",
        rules.REAL.output,
    output:
        expand("wrfout_{d}_2024-04-19_00:00:00", d=DOMAINS)
    shell:
        f"""
        cp {config['WRF_HOME']}/run/CAMtr_volume_mixing_ratio.RCP8.5 CAMtr_volume_mixing_ratio
        cp {config['WRF_HOME']}/run/ozone* .
        cp {config['WRF_HOME']}/run/RRTMG* .
        cp {config['WRF_HOME']}/run/*.TBL .
        {config['WRF_HOME']}/run/wrf.exe
        rm
        """


